# Generated by Django 3.0.4 on 2022-08-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='description',
        ),
    ]
